/* tslint:disable */
/* eslint-disable */
/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateAccountResponse,
  GetBalancesResponse,
  GetMoveResponse,
  GetOrderBookFullDefaultResponse,
  ListMovesResponse,
  ListPendingTransactionsResponse,
  ListTransactionsResponse,
  MoveResponse,
  UpdateAccountNameResponse,
} from '../models';
import {
    CreateAccountResponseFromJSON,
    CreateAccountResponseToJSON,
    GetBalancesResponseFromJSON,
    GetBalancesResponseToJSON,
    GetMoveResponseFromJSON,
    GetMoveResponseToJSON,
    GetOrderBookFullDefaultResponseFromJSON,
    GetOrderBookFullDefaultResponseToJSON,
    ListMovesResponseFromJSON,
    ListMovesResponseToJSON,
    ListPendingTransactionsResponseFromJSON,
    ListPendingTransactionsResponseToJSON,
    ListTransactionsResponseFromJSON,
    ListTransactionsResponseToJSON,
    MoveResponseFromJSON,
    MoveResponseToJSON,
    UpdateAccountNameResponseFromJSON,
    UpdateAccountNameResponseToJSON,
} from '../models';

export interface CreateAccountRequest {
    currency: string;
    name: string;
}

export interface GetBalancesRequest {
    assets?: Array<string>;
}

export interface GetMoveRequest {
    id?: string;
    clientMoveId?: string;
}

export interface ListMovesRequest {
    before?: number;
    limit?: number;
}

export interface ListPendingTransactionsRequest {
    id: number;
}

export interface ListTransactionsRequest {
    id: number;
    minRow: number;
    maxRow: number;
}

export interface MoveRequest {
    amount: string;
    debitAccountId: number;
    creditAccountId: number;
    clientMoveId?: string;
}

export interface UpdateAccountNameRequest {
    id: number;
    name: string;
}

/**
 * AccountsApi - interface
 * 
 * @export
 * @interface AccountsApiInterface
 */
export interface AccountsApiInterface {
    /**
     * This request creates an Account for the specified currency.  Please note that the balances for the Account will be displayed based on the <code>asset</code> value, which is the currency the Account is based on.  Permissions required: <code>Perm_W_Addresses</code>
     * @summary # Create account
     * @param {string} currency The currency code for the Account you want to create.  Please see the Currency section for a detailed list of currencies supported by the Luno platform.  Users must be verified to trade currency in order to be able to create an Account.  For more information on the verification process, please see &lt;a href&#x3D;\&quot;/help/en/articles/1000168396\&quot;&gt;How do I verify my identity?&lt;/a&gt;.  Users have a limit of 4 accounts per currency.
     * @param {string} name The label to use for this account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    createAccountRaw(requestParameters: CreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAccountResponse>>;

    /**
     * This request creates an Account for the specified currency.  Please note that the balances for the Account will be displayed based on the <code>asset</code> value, which is the currency the Account is based on.  Permissions required: <code>Perm_W_Addresses</code>
     * # Create account
     */
    createAccount(requestParameters: CreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAccountResponse>;

    /**
     * The list of all Accounts and their respective balances for the requesting user.  Permissions required: <code>Perm_R_Balance</code>
     * @summary # List account balances
     * @param {Array<string>} [assets] Only return balances for wallets with these currencies (if not provided, all balances will be returned). To request balances for multiple currencies, pass the parameter multiple times, e.g. &#x60;assets&#x3D;XBT&amp;assets&#x3D;ETH&#x60;.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    getBalancesRaw(requestParameters: GetBalancesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBalancesResponse>>;

    /**
     * The list of all Accounts and their respective balances for the requesting user.  Permissions required: <code>Perm_R_Balance</code>
     * # List account balances
     */
    getBalances(requestParameters: GetBalancesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBalancesResponse>;

    /**
     * Get a specific move funds instruction by either <code>id</code> or <code>client_move_id</code>. If both are provided an API error will be returned.  This endpoint is in BETA, behaviour and specification may change without any previous notice.  Permissions required: <code>MP_None</code>
     * @summary Move (BETA)
     * @param {string} [id] Get by the system ID. This is mutually exclusive with &lt;code&gt;client_move_id&lt;/code&gt; and is required if &lt;code&gt;client_move_id&lt;/code&gt; is not provided.
     * @param {string} [clientMoveId] Get by the user defined ID. This is mutually exclusive with &lt;code&gt;id&lt;/code&gt; and is required if &lt;code&gt;id&lt;/code&gt; is not provided.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    getMoveRaw(requestParameters: GetMoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetMoveResponse>>;

    /**
     * Get a specific move funds instruction by either <code>id</code> or <code>client_move_id</code>. If both are provided an API error will be returned.  This endpoint is in BETA, behaviour and specification may change without any previous notice.  Permissions required: <code>MP_None</code>
     * Move (BETA)
     */
    getMove(requestParameters: GetMoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetMoveResponse>;

    /**
     * Returns a list of the most recent moves ordered from newest to oldest. This endpoint will list up to 100 most recent moves by default.  This endpoint is in BETA, behaviour and specification may change without any previous notice.  Permissions required: <code>MP_None</code>
     * @summary ListMoves (BETA)
     * @param {number} [before] Filter to moves requested before this timestamp (Unix milliseconds)
     * @param {number} [limit] Limit to this many moves
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    listMovesRaw(requestParameters: ListMovesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListMovesResponse>>;

    /**
     * Returns a list of the most recent moves ordered from newest to oldest. This endpoint will list up to 100 most recent moves by default.  This endpoint is in BETA, behaviour and specification may change without any previous notice.  Permissions required: <code>MP_None</code>
     * ListMoves (BETA)
     */
    listMoves(requestParameters: ListMovesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListMovesResponse>;

    /**
     * Return a list of all transactions that have not completed for the Account.  Pending transactions are not numbered, and may be reordered, deleted or updated at any time.  Permissions required: <code>Perm_R_Transactions</code>
     * @summary # List pending transactions
     * @param {number} id Account ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    listPendingTransactionsRaw(requestParameters: ListPendingTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPendingTransactionsResponse>>;

    /**
     * Return a list of all transactions that have not completed for the Account.  Pending transactions are not numbered, and may be reordered, deleted or updated at any time.  Permissions required: <code>Perm_R_Transactions</code>
     * # List pending transactions
     */
    listPendingTransactions(requestParameters: ListPendingTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPendingTransactionsResponse>;

    /**
     * Return a list of transaction entries from an account.  Transaction entry rows are numbered sequentially starting from 1, where 1 is the oldest entry. The range of rows to return are specified with the <code>min_row</code> (inclusive) and <code>max_row</code> (exclusive) parameters. At most 1000 rows can be requested per call.  If <code>min_row</code> or <code>max_row</code> is non-positive, the range wraps around the most recent row. For example, to fetch the 100 most recent rows, use <code>min_row=-100</code> and <code>max_row=0</code>.  Permissions required: <code>Perm_R_Transactions</code>
     * @summary # List transactions
     * @param {number} id Account ID - the unique identifier for the specific Account.
     * @param {number} minRow Minimum of the row range to return (inclusive)
     * @param {number} maxRow Maximum of the row range to return (exclusive)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    listTransactionsRaw(requestParameters: ListTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTransactionsResponse>>;

    /**
     * Return a list of transaction entries from an account.  Transaction entry rows are numbered sequentially starting from 1, where 1 is the oldest entry. The range of rows to return are specified with the <code>min_row</code> (inclusive) and <code>max_row</code> (exclusive) parameters. At most 1000 rows can be requested per call.  If <code>min_row</code> or <code>max_row</code> is non-positive, the range wraps around the most recent row. For example, to fetch the 100 most recent rows, use <code>min_row=-100</code> and <code>max_row=0</code>.  Permissions required: <code>Perm_R_Transactions</code>
     * # List transactions
     */
    listTransactions(requestParameters: ListTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTransactionsResponse>;

    /**
     * Move funds between two of your accounts with the same currency The funds may not be moved by the time the request returns. The GET method can be used to poll for the move\'s status.  Note: moves will show as transactions, but not as transfers.  This endpoint is in BETA, behaviour and specification may change without any previous notice.  Permissions required: <code>MP_None_Write</code>
     * @summary Move (BETA)
     * @param {string} amount Amount to transfer. Must be positive.
     * @param {number} debitAccountId The account to debit the funds from.
     * @param {number} creditAccountId The account to credit the funds to.
     * @param {string} [clientMoveId] Client move ID. May only contain alphanumeric (0-9, a-z, or A-Z) and special characters (_ ; , . -). Maximum length: 255. It will be available in read endpoints, so you can use it to avoid duplicate moves between the same accounts. Values must be unique across all your successful calls of this endpoint; trying to create a move request with the same &#x60;client_move_id&#x60; as one of your past move requests will result in a HTTP 409 Conflict response.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    moveRaw(requestParameters: MoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MoveResponse>>;

    /**
     * Move funds between two of your accounts with the same currency The funds may not be moved by the time the request returns. The GET method can be used to poll for the move\'s status.  Note: moves will show as transactions, but not as transfers.  This endpoint is in BETA, behaviour and specification may change without any previous notice.  Permissions required: <code>MP_None_Write</code>
     * Move (BETA)
     */
    move(requestParameters: MoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MoveResponse>;

    /**
     * Update the name of an account with a given ID.  Permissions required: <code>Perm_W_Addresses</code>
     * @summary # Update Account Name
     * @param {number} id Account ID - the unique identifier for the specific Account.
     * @param {string} name The label to use for this account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    updateAccountNameRaw(requestParameters: UpdateAccountNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateAccountNameResponse>>;

    /**
     * Update the name of an account with a given ID.  Permissions required: <code>Perm_W_Addresses</code>
     * # Update Account Name
     */
    updateAccountName(requestParameters: UpdateAccountNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateAccountNameResponse>;

}

/**
 * 
 */
export class AccountsApi extends runtime.BaseAPI implements AccountsApiInterface {

    /**
     * This request creates an Account for the specified currency.  Please note that the balances for the Account will be displayed based on the <code>asset</code> value, which is the currency the Account is based on.  Permissions required: <code>Perm_W_Addresses</code>
     * # Create account
     */
    async createAccountRaw(requestParameters: CreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAccountResponse>> {
        if (requestParameters.currency === null || requestParameters.currency === undefined) {
            throw new runtime.RequiredError('currency','Required parameter requestParameters.currency was null or undefined when calling createAccount.');
        }

        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling createAccount.');
        }

        const queryParameters: any = {};

        if (requestParameters.currency !== undefined) {
            queryParameters['currency'] = requestParameters.currency;
        }

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/1/accounts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateAccountResponseFromJSON(jsonValue));
    }

    /**
     * This request creates an Account for the specified currency.  Please note that the balances for the Account will be displayed based on the <code>asset</code> value, which is the currency the Account is based on.  Permissions required: <code>Perm_W_Addresses</code>
     * # Create account
     */
    async createAccount(requestParameters: CreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAccountResponse> {
        const response = await this.createAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The list of all Accounts and their respective balances for the requesting user.  Permissions required: <code>Perm_R_Balance</code>
     * # List account balances
     */
    async getBalancesRaw(requestParameters: GetBalancesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBalancesResponse>> {
        const queryParameters: any = {};

        if (requestParameters.assets) {
            queryParameters['assets'] = requestParameters.assets.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/1/balance`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBalancesResponseFromJSON(jsonValue));
    }

    /**
     * The list of all Accounts and their respective balances for the requesting user.  Permissions required: <code>Perm_R_Balance</code>
     * # List account balances
     */
    async getBalances(requestParameters: GetBalancesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBalancesResponse> {
        const response = await this.getBalancesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a specific move funds instruction by either <code>id</code> or <code>client_move_id</code>. If both are provided an API error will be returned.  This endpoint is in BETA, behaviour and specification may change without any previous notice.  Permissions required: <code>MP_None</code>
     * Move (BETA)
     */
    async getMoveRaw(requestParameters: GetMoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetMoveResponse>> {
        const queryParameters: any = {};

        if (requestParameters.id !== undefined) {
            queryParameters['id'] = requestParameters.id;
        }

        if (requestParameters.clientMoveId !== undefined) {
            queryParameters['client_move_id'] = requestParameters.clientMoveId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/exchange/1/move`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetMoveResponseFromJSON(jsonValue));
    }

    /**
     * Get a specific move funds instruction by either <code>id</code> or <code>client_move_id</code>. If both are provided an API error will be returned.  This endpoint is in BETA, behaviour and specification may change without any previous notice.  Permissions required: <code>MP_None</code>
     * Move (BETA)
     */
    async getMove(requestParameters: GetMoveRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetMoveResponse> {
        const response = await this.getMoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of the most recent moves ordered from newest to oldest. This endpoint will list up to 100 most recent moves by default.  This endpoint is in BETA, behaviour and specification may change without any previous notice.  Permissions required: <code>MP_None</code>
     * ListMoves (BETA)
     */
    async listMovesRaw(requestParameters: ListMovesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListMovesResponse>> {
        const queryParameters: any = {};

        if (requestParameters.before !== undefined) {
            queryParameters['before'] = requestParameters.before;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/exchange/1/move/list_moves`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListMovesResponseFromJSON(jsonValue));
    }

    /**
     * Returns a list of the most recent moves ordered from newest to oldest. This endpoint will list up to 100 most recent moves by default.  This endpoint is in BETA, behaviour and specification may change without any previous notice.  Permissions required: <code>MP_None</code>
     * ListMoves (BETA)
     */
    async listMoves(requestParameters: ListMovesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListMovesResponse> {
        const response = await this.listMovesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Return a list of all transactions that have not completed for the Account.  Pending transactions are not numbered, and may be reordered, deleted or updated at any time.  Permissions required: <code>Perm_R_Transactions</code>
     * # List pending transactions
     */
    async listPendingTransactionsRaw(requestParameters: ListPendingTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPendingTransactionsResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling listPendingTransactions.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/1/accounts/{id}/pending`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPendingTransactionsResponseFromJSON(jsonValue));
    }

    /**
     * Return a list of all transactions that have not completed for the Account.  Pending transactions are not numbered, and may be reordered, deleted or updated at any time.  Permissions required: <code>Perm_R_Transactions</code>
     * # List pending transactions
     */
    async listPendingTransactions(requestParameters: ListPendingTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPendingTransactionsResponse> {
        const response = await this.listPendingTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Return a list of transaction entries from an account.  Transaction entry rows are numbered sequentially starting from 1, where 1 is the oldest entry. The range of rows to return are specified with the <code>min_row</code> (inclusive) and <code>max_row</code> (exclusive) parameters. At most 1000 rows can be requested per call.  If <code>min_row</code> or <code>max_row</code> is non-positive, the range wraps around the most recent row. For example, to fetch the 100 most recent rows, use <code>min_row=-100</code> and <code>max_row=0</code>.  Permissions required: <code>Perm_R_Transactions</code>
     * # List transactions
     */
    async listTransactionsRaw(requestParameters: ListTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTransactionsResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling listTransactions.');
        }

        if (requestParameters.minRow === null || requestParameters.minRow === undefined) {
            throw new runtime.RequiredError('minRow','Required parameter requestParameters.minRow was null or undefined when calling listTransactions.');
        }

        if (requestParameters.maxRow === null || requestParameters.maxRow === undefined) {
            throw new runtime.RequiredError('maxRow','Required parameter requestParameters.maxRow was null or undefined when calling listTransactions.');
        }

        const queryParameters: any = {};

        if (requestParameters.minRow !== undefined) {
            queryParameters['min_row'] = requestParameters.minRow;
        }

        if (requestParameters.maxRow !== undefined) {
            queryParameters['max_row'] = requestParameters.maxRow;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/1/accounts/{id}/transactions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTransactionsResponseFromJSON(jsonValue));
    }

    /**
     * Return a list of transaction entries from an account.  Transaction entry rows are numbered sequentially starting from 1, where 1 is the oldest entry. The range of rows to return are specified with the <code>min_row</code> (inclusive) and <code>max_row</code> (exclusive) parameters. At most 1000 rows can be requested per call.  If <code>min_row</code> or <code>max_row</code> is non-positive, the range wraps around the most recent row. For example, to fetch the 100 most recent rows, use <code>min_row=-100</code> and <code>max_row=0</code>.  Permissions required: <code>Perm_R_Transactions</code>
     * # List transactions
     */
    async listTransactions(requestParameters: ListTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTransactionsResponse> {
        const response = await this.listTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Move funds between two of your accounts with the same currency The funds may not be moved by the time the request returns. The GET method can be used to poll for the move\'s status.  Note: moves will show as transactions, but not as transfers.  This endpoint is in BETA, behaviour and specification may change without any previous notice.  Permissions required: <code>MP_None_Write</code>
     * Move (BETA)
     */
    async moveRaw(requestParameters: MoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MoveResponse>> {
        if (requestParameters.amount === null || requestParameters.amount === undefined) {
            throw new runtime.RequiredError('amount','Required parameter requestParameters.amount was null or undefined when calling move.');
        }

        if (requestParameters.debitAccountId === null || requestParameters.debitAccountId === undefined) {
            throw new runtime.RequiredError('debitAccountId','Required parameter requestParameters.debitAccountId was null or undefined when calling move.');
        }

        if (requestParameters.creditAccountId === null || requestParameters.creditAccountId === undefined) {
            throw new runtime.RequiredError('creditAccountId','Required parameter requestParameters.creditAccountId was null or undefined when calling move.');
        }

        const queryParameters: any = {};

        if (requestParameters.amount !== undefined) {
            queryParameters['amount'] = requestParameters.amount;
        }

        if (requestParameters.debitAccountId !== undefined) {
            queryParameters['debit_account_id'] = requestParameters.debitAccountId;
        }

        if (requestParameters.creditAccountId !== undefined) {
            queryParameters['credit_account_id'] = requestParameters.creditAccountId;
        }

        if (requestParameters.clientMoveId !== undefined) {
            queryParameters['client_move_id'] = requestParameters.clientMoveId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/exchange/1/move`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MoveResponseFromJSON(jsonValue));
    }

    /**
     * Move funds between two of your accounts with the same currency The funds may not be moved by the time the request returns. The GET method can be used to poll for the move\'s status.  Note: moves will show as transactions, but not as transfers.  This endpoint is in BETA, behaviour and specification may change without any previous notice.  Permissions required: <code>MP_None_Write</code>
     * Move (BETA)
     */
    async move(requestParameters: MoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MoveResponse> {
        const response = await this.moveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update the name of an account with a given ID.  Permissions required: <code>Perm_W_Addresses</code>
     * # Update Account Name
     */
    async updateAccountNameRaw(requestParameters: UpdateAccountNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateAccountNameResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateAccountName.');
        }

        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling updateAccountName.');
        }

        const queryParameters: any = {};

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/1/accounts/{id}/name`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateAccountNameResponseFromJSON(jsonValue));
    }

    /**
     * Update the name of an account with a given ID.  Permissions required: <code>Perm_W_Addresses</code>
     * # Update Account Name
     */
    async updateAccountName(requestParameters: UpdateAccountNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateAccountNameResponse> {
        const response = await this.updateAccountNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
