/* tslint:disable */
/* eslint-disable */
/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressMeta
 */
export interface AddressMeta {
    /**
     * 
     * @type {string}
     * @memberof AddressMeta
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressMeta
     */
    value?: string;
}

/**
 * Check if a given object implements the AddressMeta interface.
 */
export function instanceOfAddressMeta(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressMetaFromJSON(json: any): AddressMeta {
    return AddressMetaFromJSONTyped(json, false);
}

export function AddressMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': !exists(json, 'label') ? undefined : json['label'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function AddressMetaToJSON(value?: AddressMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'value': value.value,
    };
}

