/* tslint:disable */
/* eslint-disable */
/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountBalance } from './AccountBalance';
import {
    AccountBalanceFromJSON,
    AccountBalanceFromJSONTyped,
    AccountBalanceToJSON,
} from './AccountBalance';

/**
 * 
 * @export
 * @interface BalanceList
 */
export interface BalanceList {
    /**
     * 
     * @type {Array<AccountBalance>}
     * @memberof BalanceList
     */
    balance?: Array<AccountBalance>;
}

/**
 * Check if a given object implements the BalanceList interface.
 */
export function instanceOfBalanceList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BalanceListFromJSON(json: any): BalanceList {
    return BalanceListFromJSONTyped(json, false);
}

export function BalanceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'balance': !exists(json, 'balance') ? undefined : ((json['balance'] as Array<any>).map(AccountBalanceFromJSON)),
    };
}

export function BalanceListToJSON(value?: BalanceList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'balance': value.balance === undefined ? undefined : ((value.balance as Array<any>).map(AccountBalanceToJSON)),
    };
}

