/* tslint:disable */
/* eslint-disable */
/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * CryptoDetails contains a transaction's cryptocurrency address
 * and transaction id
 * @export
 * @interface CryptoDetails
 */
export interface CryptoDetails {
    /**
     * 
     * @type {string}
     * @memberof CryptoDetails
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof CryptoDetails
     */
    txid?: string;
}

/**
 * Check if a given object implements the CryptoDetails interface.
 */
export function instanceOfCryptoDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CryptoDetailsFromJSON(json: any): CryptoDetails {
    return CryptoDetailsFromJSONTyped(json, false);
}

export function CryptoDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': !exists(json, 'address') ? undefined : json['address'],
        'txid': !exists(json, 'txid') ? undefined : json['txid'],
    };
}

export function CryptoDetailsToJSON(value?: CryptoDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'txid': value.txid,
    };
}

