/* tslint:disable */
/* eslint-disable */
/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CryptoDetails } from './CryptoDetails';
import {
    CryptoDetailsFromJSON,
    CryptoDetailsFromJSONTyped,
    CryptoDetailsToJSON,
} from './CryptoDetails';
import type { TradeDetails } from './TradeDetails';
import {
    TradeDetailsFromJSON,
    TradeDetailsFromJSONTyped,
    TradeDetailsToJSON,
} from './TradeDetails';

/**
 * 
 * @export
 * @interface DetailFields
 */
export interface DetailFields {
    /**
     * 
     * @type {CryptoDetails}
     * @memberof DetailFields
     */
    cryptoDetails?: CryptoDetails;
    /**
     * 
     * @type {TradeDetails}
     * @memberof DetailFields
     */
    tradeDetails?: TradeDetails;
}

/**
 * Check if a given object implements the DetailFields interface.
 */
export function instanceOfDetailFields(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DetailFieldsFromJSON(json: any): DetailFields {
    return DetailFieldsFromJSONTyped(json, false);
}

export function DetailFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cryptoDetails': !exists(json, 'crypto_details') ? undefined : CryptoDetailsFromJSON(json['crypto_details']),
        'tradeDetails': !exists(json, 'trade_details') ? undefined : TradeDetailsFromJSON(json['trade_details']),
    };
}

export function DetailFieldsToJSON(value?: DetailFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'crypto_details': CryptoDetailsToJSON(value.cryptoDetails),
        'trade_details': TradeDetailsToJSON(value.tradeDetails),
    };
}

