/* tslint:disable */
/* eslint-disable */
/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * GetFeeInfoResponse response object for get fee info calls
 * @export
 * @interface GetFeeInfoResponse
 */
export interface GetFeeInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof GetFeeInfoResponse
     */
    makerFee?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFeeInfoResponse
     */
    takerFee?: string;
    /**
     * 
     * @type {string}
     * @memberof GetFeeInfoResponse
     */
    thirtyDayVolume?: string;
}

/**
 * Check if a given object implements the GetFeeInfoResponse interface.
 */
export function instanceOfGetFeeInfoResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetFeeInfoResponseFromJSON(json: any): GetFeeInfoResponse {
    return GetFeeInfoResponseFromJSONTyped(json, false);
}

export function GetFeeInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFeeInfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'makerFee': !exists(json, 'maker_fee') ? undefined : json['maker_fee'],
        'takerFee': !exists(json, 'taker_fee') ? undefined : json['taker_fee'],
        'thirtyDayVolume': !exists(json, 'thirty_day_volume') ? undefined : json['thirty_day_volume'],
    };
}

export function GetFeeInfoResponseToJSON(value?: GetFeeInfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'maker_fee': value.makerFee,
        'taker_fee': value.takerFee,
        'thirty_day_volume': value.thirtyDayVolume,
    };
}

