/* tslint:disable */
/* eslint-disable */
/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOrderBookFullDefaultResponse
 */
export interface GetOrderBookFullDefaultResponse {
    /**
     * Unique error reference
     * @type {string}
     * @memberof GetOrderBookFullDefaultResponse
     */
    code?: string;
    /**
     * Verbose error message
     * @type {string}
     * @memberof GetOrderBookFullDefaultResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the GetOrderBookFullDefaultResponse interface.
 */
export function instanceOfGetOrderBookFullDefaultResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetOrderBookFullDefaultResponseFromJSON(json: any): GetOrderBookFullDefaultResponse {
    return GetOrderBookFullDefaultResponseFromJSONTyped(json, false);
}

export function GetOrderBookFullDefaultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrderBookFullDefaultResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function GetOrderBookFullDefaultResponseToJSON(value?: GetOrderBookFullDefaultResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
    };
}

