/* tslint:disable */
/* eslint-disable */
/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
} from './Transaction';

/**
 * ListTransactionsResponse response
 * @export
 * @interface ListTransactionsResponse
 */
export interface ListTransactionsResponse {
    /**
     * 
     * @type {string}
     * @memberof ListTransactionsResponse
     */
    id?: string;
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof ListTransactionsResponse
     */
    transactions?: Array<Transaction>;
}

/**
 * Check if a given object implements the ListTransactionsResponse interface.
 */
export function instanceOfListTransactionsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListTransactionsResponseFromJSON(json: any): ListTransactionsResponse {
    return ListTransactionsResponseFromJSONTyped(json, false);
}

export function ListTransactionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTransactionsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'transactions': !exists(json, 'transactions') ? undefined : ((json['transactions'] as Array<any>).map(TransactionFromJSON)),
    };
}

export function ListTransactionsResponseToJSON(value?: ListTransactionsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'transactions': value.transactions === undefined ? undefined : ((value.transactions as Array<any>).map(TransactionToJSON)),
    };
}

