/* tslint:disable */
/* eslint-disable */
/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
} from './Order';

/**
 * ListOrdersResponse response
 * @export
 * @interface ListOrdersResponse
 */
export interface ListOrdersResponse {
    /**
     * 
     * @type {Array<Order>}
     * @memberof ListOrdersResponse
     */
    orders?: Array<Order>;
}

/**
 * Check if a given object implements the ListOrdersResponse interface.
 */
export function instanceOfListOrdersResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListOrdersResponseFromJSON(json: any): ListOrdersResponse {
    return ListOrdersResponseFromJSONTyped(json, false);
}

export function ListOrdersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrdersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orders': !exists(json, 'orders') ? undefined : ((json['orders'] as Array<any>).map(OrderFromJSON)),
    };
}

export function ListOrdersResponseToJSON(value?: ListOrdersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orders': value.orders === undefined ? undefined : ((value.orders as Array<any>).map(OrderToJSON)),
    };
}

