/* tslint:disable */
/* eslint-disable */
/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Transfer } from './Transfer';
import {
    TransferFromJSON,
    TransferFromJSONTyped,
    TransferToJSON,
} from './Transfer';

/**
 * ListTransfersResponse response for /api/1/transfers
 * @export
 * @interface ListTransfersResponse
 */
export interface ListTransfersResponse {
    /**
     * 
     * @type {Array<Transfer>}
     * @memberof ListTransfersResponse
     */
    transfers?: Array<Transfer>;
}

/**
 * Check if a given object implements the ListTransfersResponse interface.
 */
export function instanceOfListTransfersResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListTransfersResponseFromJSON(json: any): ListTransfersResponse {
    return ListTransfersResponseFromJSONTyped(json, false);
}

export function ListTransfersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTransfersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transfers': !exists(json, 'transfers') ? undefined : ((json['transfers'] as Array<any>).map(TransferFromJSON)),
    };
}

export function ListTransfersResponseToJSON(value?: ListTransfersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transfers': value.transfers === undefined ? undefined : ((value.transfers as Array<any>).map(TransferToJSON)),
    };
}

