/* tslint:disable */
/* eslint-disable */
/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PublicTrade } from './PublicTrade';
import {
    PublicTradeFromJSON,
    PublicTradeFromJSONTyped,
    PublicTradeToJSON,
} from './PublicTrade';

/**
 * ListTradesResponse response for /api/1/trades
 * @export
 * @interface ListTradesResponse
 */
export interface ListTradesResponse {
    /**
     * 
     * @type {Array<PublicTrade>}
     * @memberof ListTradesResponse
     */
    trades?: Array<PublicTrade>;
}

/**
 * Check if a given object implements the ListTradesResponse interface.
 */
export function instanceOfListTradesResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListTradesResponseFromJSON(json: any): ListTradesResponse {
    return ListTradesResponseFromJSONTyped(json, false);
}

export function ListTradesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTradesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'trades': !exists(json, 'trades') ? undefined : ((json['trades'] as Array<any>).map(PublicTradeFromJSON)),
    };
}

export function ListTradesResponseToJSON(value?: ListTradesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'trades': value.trades === undefined ? undefined : ((value.trades as Array<any>).map(PublicTradeToJSON)),
    };
}

