/* tslint:disable */
/* eslint-disable */
/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * SendFeeResponse response object for send fee call
 * @export
 * @interface SendFeeResponse
 */
export interface SendFeeResponse {
    /**
     * 
     * @type {string}
     * @memberof SendFeeResponse
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof SendFeeResponse
     */
    fee?: string;
}

/**
 * Check if a given object implements the SendFeeResponse interface.
 */
export function instanceOfSendFeeResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SendFeeResponseFromJSON(json: any): SendFeeResponse {
    return SendFeeResponseFromJSONTyped(json, false);
}

export function SendFeeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendFeeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'fee': !exists(json, 'fee') ? undefined : json['fee'],
    };
}

export function SendFeeResponseToJSON(value?: SendFeeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currency': value.currency,
        'fee': value.fee,
    };
}

